			self.errors.append("Exception when GETing from FTL: " + str(e))
